name = "Animations"
uuid = "27a7e980-b3e6-11e9-2bcd-0b925532e340"
authors = ["Julius Krumbiegel <julius.krumbiegel@gmail.com>"]
version = "0.4.1"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"

[compat]
julia = "1"
Colors = "0"
